language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --upgrade-strategy eager --upgrade tox-travis codecov .[test]

script:
  - tox
  - coverage combine .coverage-py*
  - codecov
