dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install --upgrade-strategy eager --upgrade tox-travis codecov .[test]

script:
  - tox
  - coverage combine .coverage-py*
  - codecov

jobs:
  include:
    - stage: Publish to PyPI
      python: "3.7"
      # Do not inherit `install` and `script` from above.  No reason to run
      # checks again on deploy.
      install: 'true'
      script: 'true'
      deploy:
        provider: pypi
        on:
          tags: true
          repo: pedrohdz/muextensions
          condition: '$TRAVIS_TAG =~ ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
        user: '__token__'
        # -- PyPI - Production
        password:
          secure: 'VgrMLGkug+vTtfiuBJJRCVMqYL+sjB5aHMUdaKs1VIwbQNaK1qVMaIDJF1naK2i6p7WytZwqxFK/elZ/BsfqidPkoaAsFix2OjGwSCn8KKd4f4XPcMGo/D+Rs8UgfD6P9xFucL4VGItmoWrANP3bOtFcOlGJqKv3/2eN46cF/dNyJd8aeABeSX5oAXX9yGSloXMHE+5KCLLCDbyCI2qKGWKICcBqPAg6LZbcnlSuXYnT94FXvnUpGEvuF6B3pRXAG8gmPELzeTbKFb9QGoblGapmfPjn4qY9Q2W4u3IOT+UDgvqATfl8WmLMwU5KYdjO5KDEJuE1gKf6qqz3oYBfE2OfyAexNDFpmBEHS3qlsCn26JDq5gplQvKj/A8CO7XTpgtCwLSC+VgCYsB9rdWYyK39PzooUWmsSSGvmTb3Ht5ZSRzFE/iYbKiykHeiKug1u7opQ9aaRfZRkmYPE/v6RcCY3MNVs3Vk2TWp1hX60A1f0yg7/5N7+hnEcYDGLPjro7yGrEk3aZ8GmqPBYWQXH5LG9b+DDNxsy+TUwocurLH7RbjgzDJ0zFYvZO+hMPySLRUj1imY6M6zRuQDUdD8+IM7EC9QRVD4bbkgdSYtCmhuIe4YKQ5Vp3/IuukO2gxuDoX/M/seb9l7ZWz3WWtiRtkDhLHrhNUIHDKw9yqauaY='
        # -- PyPI - Testing
        #server: https://test.pypi.org/legacy/
        #password:
        #  secure: XtEyLvhpJCVVmO6+HORWOitefPIpvQToZO+bH8FCvOrc62BYug+8KCD+y0y2v9hlYUT6dBaHbN+bmIREVFEK9/lrJGotQU85QKP3we80RM6vmstPK8nPF8w2Jx2mxVOv0x4Wsq3BvFqW3cKR0yN2fkmbINIl7eDGCYUThSpVJR0oiZHZfhviG9Qg+99GozNwQV5o23f14gKhoSVTszQYz0t4n3bZZ19DbDZqmHaYUN/0bIriW24K+dMXd1yk5ot4EN8ojzqidUBBRMIT76qYokp3u/ZPFTNoikcRK60RunpHgx7P2UHLl6nEq6EJWinRcHOnQk8jlhnTuyaCuexsRE/FC/pvWaPlvQWx/9JoawArnukCWhPa/gWVPpS4b4GoshpRPg18yFSHvc66JdO3EtNH3MBdVTMRpbrx8heIAM/RrOekP/yL6dcPxPk5qG8BS8LCqsb4U2XK3RFHnaUn9SaK0mevd90iDq/TbJrbX4/htKZNSZTfLLPyY+SvphSbv5E1u68O6ED2rN992LLP8F+g2+3qNEh6iAfyQZ1fYETOEEcXcasVDknz+P+Sts7t6zt4Av/gVS129duJ4MwQ2vjxhi5bfdrTG8dPnKjKBqqngdljgGrnPByr8yZnf+UK7W82X5S50xtRHbSYEYewVRYcpJPw47H0wpZhM0z6bKw=
